spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/dbs/sparta
    username: sa
    password:

  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=


#jdbc:h2:mem:db;MODE=MYSQL;
#jdbc:h2:tcp://localhost/~/dbs/sparta